product/urls.py
from django.conf.urls import url
from product import views

urlpatterns = [
    url(r'^$', views.home, name='home'),
    url(r'^products/$', views.ProductsListView.as_view(), name='product_list'),
    url(r'^products/(?P<slug>[\w-]+)/$', views.ProductDetailView.as_view(),
        name='product_detail'),
    url(r'^signup/$', views.sign_up, name='sign_up'),
    url(r'^like/(?P<product_id>[0-9]+)$', views.like_product, name='like')
]

test_app/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from product import urls as product_urls

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/$', 'django.contrib.auth.views.login',
        {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'next_page': '/'}, name='auth_logout'),
    url(r'^', include(product_urls))
]

product/models.py
# -*- coding: utf-8 -*-
from datetime import timedelta
from django.core.validators import MinLengthValidator, RegexValidator
from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.utils import timezone


class Product(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(max_digits=16, decimal_places=2)
    created_at = models.DateTimeField(default=timezone.now, editable=False)
    modified_at = models.DateTimeField(default=timezone.now)

    def last_comments(self):
        return self.comment_set.filter(
            created_at__gte=(timezone.now() - timedelta(hours=24)))

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.slug)])


class Like(models.Model):
    product = models.ForeignKey(Product, default=None)
    user = models.ForeignKey(User)

    class Meta:
        unique_together = ("product", "user", )

    def __unicode__(self):
        return self.user.username

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.product.slug)])


class Comment(models.Model):
    user = models.ForeignKey(User, default=None, null=True, blank=True)
    name = models.CharField(
        max_length=16, blank=True, null=False,
        validators=[
            MinLengthValidator(4),
            RegexValidator(
                regex=u'^[a-zA-Z0-9а-я-А-Я]*$',
                message='Username must be Alphanumeric',
                code='invalid_username'
            )
        ])
    product = models.ForeignKey(Product)
    text = models.TextField(
        blank=False, null=False, validators=[MinLengthValidator(20)])
    created_at = models.DateTimeField(default=timezone.now, editable=False)

    class Meta:
        ordering = ['-created_at']

    def __unicode__(self):
        return self.text

    def get_absolute_url(self):
        return reverse('product_detail', args=[str(self.product.slug)])

    def get_author(self):
        if self.user:
            user = self.user.username
        elif self.name:
            user = self.name
        else:
            user = 'Anonym'
        return user

product/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import ModelForm
from django.contrib.auth.models import User
from product.models import Comment


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email')


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        name = forms.CharField(min_length=4)
        exclude = ('user', 'product', 'created_at')

product/views.py
import json
import logging
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import login
from django.http import HttpResponseRedirect
from django.views.decorators.http import require_POST
from django.views.generic import DetailView
from django.views.generic.list import ListView
from django.utils import six

from product.forms import SignUpForm
from product.models import Product, Like
from product.forms import CommentForm
from product.utils import is_liked_product, ajax_required

logger = logging.getLogger(__name__)


def home(request):
    return render(request, 'home.html')


class ProductsListView(ListView):
    model = Product
    paginate_by = 5
    template_name = 'product_list.html'
    ordering = 'name'

    def get_queryset(self):
        qs = super(ProductsListView, self).get_queryset()
        custom_order = ['like_count', '-like_count']
        self.ordering = self.request.GET.get('order_by', None)
        if self.ordering in custom_order:
            qs = qs.annotate(like_count=Count('like')).order_by(
                self.ordering)

        ordering = self.get_ordering()
        if ordering and ordering not in custom_order:
            if isinstance(ordering, six.string_types):
                ordering = (ordering,)
            qs = qs.order_by(*ordering)
        return qs

    def get_context_data(self, **kwargs):
        context = super(ProductsListView, self).get_context_data(**kwargs)
        context['ordering'] = self.get_ordering()
        return context


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'product'

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        return context

    def get(self, request, **kwargs):
        form = CommentForm()
        return render(
            self.request, 'product_detail.html',
            {'form': form, 'product': self.get_object()}
        )

    def post(self, request, **kwargs):
        form = CommentForm(self.request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = self.request.user \
                if self.request.user.is_authenticated() else None
            comment.product = self.get_object()
            comment.save()
            messages.success(self.request, 'Comment successfully added')
            return render(
                self.request, 'product_detail.html',
                {'form': CommentForm(), 'product': self.get_object()})
        else:
            messages.error(self.request, 'Can\'t add you comment')
            return render(
                self.request, 'product_detail.html',
                {'form': form, 'product': self.get_object()})


def sign_up(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            user = authenticate(
                username=form.cleaned_data['username'],
                password=form.cleaned_data['password1'])
            login(request, user)
            return HttpResponseRedirect(reverse('product_list'))
    else:
        form = SignUpForm()
    return render(request, 'signup.html', {'form': form})


@login_required
@require_POST
@ajax_required
def like_product(request, product_id):
    data = {}
    product = Product.objects.filter(id=product_id).first()
    if product and not is_liked_product(product, request.user):
        try:
            Like.objects.create(product=product, user=request.user)
            messages.success(request, 'like was added', extra_tags='add')
        except Exception as e:
            info = 'Can\'t add like'
            messages.error(request, info)
            logger.info(info)
            logger.error(e)
    elif product and is_liked_product(product, request.user):
        try:
            Like.objects.filter(product=product, user=request.user).delete()
            messages.success(request, 'like was removed', extra_tags='delete')
        except Exception as e:
            info = 'Can\'t remove like'
            messages.error(request, info)
            logger.info(info)
            logger.error(e)
    else:
        messages.error(request, 'Wrong product')
    data['response'] = 'ajaxResponse'
    return HttpResponse(json.dumps(data), content_type='application/json')

product/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block head %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Products App{% endblock %}</title>
        <script src="{% static 'js/jquery.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" media="screen">
        <link href="{% static 'css/custom.css' %}" rel="stylesheet" type="text/css" >
    {% endblock head %}

    {% block extra_head %}{% endblock extra_head %}
</head>

<body>
{% block nav %}
    <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'home' %}"></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                    <li><a class="menu" href="{% url 'home' %}">Home</a></li>
                    <li><a class="menu" href="{% url 'product_list' %}">Products</a></li>
                    <li><a class="menu" href="{% url 'admin:index' %}">Admin</a></li>
                    {% if user.is_authenticated %}
                        <li><a class="logout" href="{% url 'auth_logout' %}">LogOut</a></li>
                    {% else %}
                        <li><a class="login" href="{% url 'login' %}?next={% url 'home' %}">LogIn</a></li>
                        <li><a class="signup" href="{% url "sign_up" %}">SignUp</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock nav %}
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                {% block content %}{% endblock content %}
            </div>
        </div>
    </div>
</body>
</html>

product/templates/home.html
{% extends 'base.html' %}

product/templates/includes/comments_form.html
<h4>Add comment</h4>
<div class="col-md-8 col-sm-offset-4">
    <form class="form-horizontal" role="form" method="post">
        {% csrf_token %}
        {% if not user.is_authenticated %}
            <div class="row">
                <div class="control-group error  {% if form.name.errors %}has-error{% endif %}">
                    <div class="controls">
                        <div class="col-md-6 col-xs-3">
                            <input type="text" class="form-control" id="{{ form.name.id_for_label }}" name="name" placeholder="{{ form.name.label }}" value="{% if form.name.value %}{{ form.name.value }}{% endif %}">
                        </div>
                        <div class="col-md-5 col-xs-6">
                            {% if form.name.errors %}
                                <p class="text-danger"> {{ form.name.errors|join:'<br />' }}</p>
                            {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        {% endif %}
        <div class="clear"></div>
        <div class="row">
            <div class="control-group error {% if form.text.errors %}has-error{% endif %}">
                <div class="controls">
                    <div class="col-md-6 col-xs-3">
                        <textarea class="form-control" rows="4" id="{{ form.text.id_for_text }}" name="text" placeholder="Enter your text here">{% if form.text.value %}{{ form.text.value }}{% endif %}</textarea>
                    </div>
                    <div class="col-md5 col-xs-6">
                        {% if form.text.errors %}
                            <span class="text-danger">{{ form.text.errors|join:'<br />' }}</span>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
        <div class="clear"></div>
        <div class="row">
            <div class="control-group error">
                <div class="col-md-6 col-xs-3">
                    <input id="submit" name="submit" type="submit" value="Send" class="btn btn-primary">
                </div>
            </div>
        </div>
    </form>
</div>

product/templates/includes/comments_list.html
{% load tz %}
{% if comments %}
    <h4><strong>Comments:</strong></h4>
{% endif %}

{% for comment in comments %}
    <div class="comment">
        <div class="time">
            <span class="italic"><strong>Added at</strong></span> {{ comment.created_at|date:'Y-m-d H:i' }}
            <span class="italic"><strong>by</strong></span> {{ comment.get_author }}
        </div>
        <div class="body">{{ comment.text|linebreaks }}</div>
        <hr class="divider">
    </div>
{% endfor %}

product/templates/includes/pagination.html
{% if is_paginated %}
    <ul class="pagination">
        {% if page_obj.has_previous %}
            <li>
                <span><a href="?page={{ page_obj.previous_page_number }}{% if ordering %}&order_by={{ ordering }}{% endif %}">Previous</a></span>
            </li>
        {% endif %}
        <li class="">
            <span>Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.</span>
        </li>
        {% if page_obj.has_next %}
            <li>
                <span><a href="?page={{ page_obj.next_page_number }}{% if ordering %}&order_by={{ ordering }}{% endif %}">Next</a></span>
            </li>
        {% endif %}
    </ul>
{% endif %}

product/templates/product_detail.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load product_tags %}

{% block extra_head %}
    <script src="{% static 'js/jquery.cookie-1.4.1.js' %}"></script>
    <script src="{% static 'js/csrf.js' %}"></script>
    <script src="{% static 'js/like.js' %}"></script>
    <script>
    var productId = {{ product.id }};
    </script>
{% endblock extra_head %}
    {% block content %}
        <row>
        <div class="message-row">
            <ul id="'messages" class="messages">
                {% if messages %}
                    {% for message in messages %}
                        <p{% if message.tags %} class="{{ message.tags }}"{% endif %}>
                            {{ message }}
                        </p>
                    {% endfor %}
                {% endif %}
            </ul>
        </div>
            <h3 class="text-uppercase">{{ product.name|safe }}</h3>
            <p class="text-left"><strong>Description:</strong> {{ product.description|safe }}</p>
            <p class="text-left"><strong>Price:</strong> {{ product.price }}</p>
            <p class="text-left"><strong>Like</strong>
                {% if user and user.is_authenticated %}
                    <input data-product_id={{ product.id }} type="checkbox" class="send-like" {% is_liked product 'checked' '' %}>
                {% endif %}
                <span id="like_for_{{product.id}}">{{ product.like_set.count }}</span></p>
        </row>
        <div class="row">
        {% include 'includes/comments_form.html' %}
        </div>
        <hr class="divider">
        <div class="clear-big"></div>
        <div class="row">
        <div class="col-md-12 col-xs-2"></div>
        <div class="col-md-12 col-xs-8">
            {% with product.last_comments as comments %}
                {% include 'includes/comments_list.html' %}
            {% endwith %}
        </div>
        <div class="col-md-12 col-xs-2"></div>
        </div>
    {% endblock %}

product/templates/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block extra_head %}
    <script src="{% static 'js/order.js' %}"></script>
{% endblock extra_head %}

{% block content %}
    Order by:
    <select class="selectpicker">
        {% with request.GET.order_by as active_order %}
            <option value="name" {% if active_order == 'name' %}selected{% endif %}>Name, A-Z</option>
            <option value="-name" {% if active_order == '-name' %}selected{% endif %}>Name, Z-A</option>
            <option value="like_count" {% if active_order == 'like_count' %}selected{% endif %}>Like, 0-9</option>
            <option value="-like_count" {% if active_order == '-like_count' %}selected{% endif %}>Like, 9-0</option>
        {% endwith %}
    </select>
    <div class="clear"></div>
    <table class="table table-bordered">
        <thead>
        <tr>
            <td>Product name</td>
            <td>Description</td>
            <td>Price</td>
            <td>likes</td>
        </tr>
        </thead>
        <tbody>
        {% for product in object_list %}
            <tr>
                <td><a href="{% url 'product_detail' product.slug %}">{{ product.name }}</a></td>
                <td>{{ product.description}}</td>
                <td>{{ product.price }}</td>
                <td>{{ product.like_set.count }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    {% include 'includes/pagination.html' %}

{% endblock content %}

product/templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <form  method="post">
        {% csrf_token %}
        {% for field in form %}
            <div class="row">
                <div class="form-group {% if field.errors %}has-error{% endif %} col-sm-offset-4">
                    <label for="{{ field.id_for_label }}" class="col-sm-1 control-label">{{ field.label }}</label>
                    <div class="col-sm-6 col-sm-offset-1">
                        <input type="text" class="form-control" id="{{ field.id_for_label }}" name="{{ field.name }}" value="{% if field.value %}{{ field.value }}{% endif %}">
                        {% if field.errors %}
                            <p class="text-danger"> {{ field.errors|join:'<br />' }}</p>
                        {% endif %}
                    </div>
                </div>
            </div>
        {% endfor %}
        <div class="clear"></div>
        <div class="row">
            <div class="control-group col-sm-offset-4">
                <div class="col-md-6 col-xs-3">
                    <input id="submit" name="submit" type="submit" value="Apply" class="btn btn-primary">
                </div>
            </div>
        </div>
    </form>
{% endblock %}